// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// expand_half_grid
List expand_half_grid(CharacterVector x);
RcppExport SEXP _coloc_expand_half_grid(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_half_grid(x));
    return rcpp_result_gen;
END_RCPP
}
// expand_r
List expand_r(NumericMatrix x);
RcppExport SEXP _coloc_expand_r(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_r(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coloc_expand_half_grid", (DL_FUNC) &_coloc_expand_half_grid, 1},
    {"_coloc_expand_r", (DL_FUNC) &_coloc_expand_r, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_coloc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
