# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expand_half_grid <- function(x) {
    .Call('_coloc_expand_half_grid', PACKAGE = 'coloc', x)
}

expand_r <- function(x) {
    .Call('_coloc_expand_r', PACKAGE = 'coloc', x)
}

